external_components:
  - source: github://dyrvigk/sprsun@main
    refresh: 0s


nilan:

sensor:
 
 
  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Inlet Temp
    id: inlet_temp
    register_type: holding
    address: 188
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: return x * 0.1;
    accuracy_decimals: 2
    
  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} HotWater Temp
    id: hotwater_temp
    register_type: holding
    address: 195
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: return x * 0.1;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Udendørs Temp
    id: ambi_temp
    register_type: holding
    address: 190
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: return x * 0.1;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Outlet Temp
    id: outlet_temp
    register_type: holding
    address: 189
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: return x * 0.1;
    accuracy_decimals: 2
 
 

  

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Suction Gas Temp
    id: suct_gas_temp
    register_type: holding
    address: 191
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: return x * 0.1;
    accuracy_decimals: 2

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Coil Temp
    id: coil_temp
    register_type: holding
    address: 196
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: return x * 0.1;
    accuracy_decimals: 2
    
    
  
    
  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Fan 1
    id: dc_fan_1_speed
    register_type: holding
    address: 199
    unit_of_measurement: "RPM"
    #device_class: "frequency"
    value_type: U_WORD
    filters:
      - lambda: return x * 1.0;
    

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Fan 2
    id: dc_fan_2_speed
    register_type: holding
    address: 201
    unit_of_measurement: "RPM"
    #device_class: "frequency"
    value_type: U_WORD
    filters:
      - lambda: return x * 1.0;
    
    
  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Evaporator Temp
    id: evap_temp
    register_type: holding
    address: 206
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_type: S_WORD
    filters:
      - lambda: return x * 0.1;
    accuracy_decimals: 2
  
  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Suction Pressure
    id: suct_press
    register_type: holding
    address: 194
    unit_of_measurement: "bar"
    device_class: "pressure"
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Discharge Pressure
    id: disch_press
    register_type: holding
    address: 193
    unit_of_measurement: "bar"
    device_class: "pressure"
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Fan output
    id: fan_output
    register_type: holding
    address: 197
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Pump output
    id: pump_output
    register_type: holding
    address: 198
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1  

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Required cap
    id: required_capasity
    register_type: holding
    address: 203
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1  

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Actual cap
    id: actual_capasity
    register_type: holding
    address: 204
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1  

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Actual speed
    id: actual_speed
    register_type: holding
    address: 205
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1    
    

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Electronic expansion valve opening
    id: eev_opening
    register_type: holding
    address: 207
    value_type: U_WORD
    filters:
      - multiply: 0.01
    accuracy_decimals: 1    
    
  

select:
  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} Work Mode
    #icon: "mdi:fan"
    id: p06_unit_mode
    address: 000
    entity_category: config
    value_type: U_WORD
    optimistic: false
    skip_updates: 6
    optionsmap:
      "Cooling": 0
      "Heating": 1
      "HotWater": 2
      "HotWater + Cooling": 3
      "HotWater + Heating": 4




number: 

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: ${friendly_name} hotwater_setpoint
    address: 003
    unit_of_measurement: "°C"
    #icon: "mdi:fan-speed-1"
    id: p04_hotwater_setpoint
    value_type: U_WORD
    min_value: 10
    max_value: 55
    lambda: "return x * 0.1;"
    write_lambda: "return x / 0.1;"
    step: 1
    mode: slider
    entity_category: config
    skip_updates: 6

  - platform: modbus_controller
    modbus_controller_id: sprsun_pc
    name: "Fan mode set"
    id: sprsun_fan_mode_set
    min_value: 0
    max_value: 3
    step: 1.0
    address: 12
    force_new_range: true
    use_write_multiple: true

climate:
  - platform: nilan
    name: Nilan
    current_temp_sensor_id: hotwater_temp
    target_temp_sensor_id: p04_hotwater_setpoint
    fan_speed_sensor_id: sprsun_fan_mode_set
    mode_select_id: p06_unit_mode
 
  
